project:
  name: test-java-rest-jpa

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

server:
  port: 8080
  error.whitelabel.enabled: false

spring:
  application:
    name: ${project.name}
  main.banner-mode: 'off'
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./db/localdb;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: ''

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
